pact-foundation/pact_broker-client

- README.md
- lib/pact_broker/client/base_client.rb
- lib/pact_broker/client/pact_broker_client.rb
- lib/pact_broker/client/pacticipants.rb
- lib/pact_broker/client/publish_pacts.rb
- lib/pact_broker/client/tasks/publication_task.rb
- lib/pact_broker/client/versions.rb
- spec/lib/pact_broker/client/base_client_spec.rb
- spec/lib/pact_broker/client/pact_broker_client_spec.rb
- spec/lib/pact_broker/client/pacticipants_spec.rb
- spec/lib/pact_broker/client/publish_pacts_spec.rb
- spec/lib/pact_broker/client/tasks/publication_task_spec.rb
- spec/lib/pact_broker/client/versions_spec.rb
Hi,
I've forked the pact, pact-support and pact_broker-client repository and made the changes on the 'basic_auth' branch for each project and created pull request.
The main changes are:
pass the basic auth option to PactFile open method
* added the basic auth options in dsl 
```ruby
honours_pact_with 'ServiceConsumer' do
pact_uri 'http://pact-broker-url/consumer/ServiceConsumer/latest', {username: 'user', password: 'pass'}
end
```
* when running pact:verify:at['pact_broker_url'] task, currently I just let users to set environment variables PACT_REPO_USERNAME, PACT_REPO_PASSWORD for the basic auth information.  I am not sure whether it's good enough.
pass optional pact_broker_basic_auth in the PublicationTask
```ruby
task.pact_broker_basic_auth =  { username: 'basic_auth_user', password: …
```
> added pact_broker_basic_auth options to publish task

- spec/pacts/pact_broker_client-pact_broker.json
- spec/service_providers/extra_goodies_spec.rb
- spec/service_providers/pact_broker_client_publish_spec.rb
- spec/service_providers/pact_broker_client_retrive_pact_spec.rb
pact_broker might respond with `charset` field in `Content-Type` header.
Related with https://github.com/bethesque/pact_broker/pull/46
> Loosen content type header expectation

- lib/pact_broker/client/pacts.rb
- lib/pact_broker/client/publish_pacts.rb
- pact-broker-client.gemspec
- spec/lib/pact_broker/client/publish_pacts_spec.rb
Sometimes it is useful for developers using Pact to warn this, in my opinion. How about?
I tested this with my own pact broker.
> Warn on overwritting pact file

- lib/pact_broker/client/pacts.rb
- spec/pacts/pact_broker_client-pact_broker.json
- spec/service_providers/pact_broker_client_retrieve_all_pacts_for_provider_spec.rb
- spec/support/latest_pacts_for_provider.json
This PR makes it possible to retrieve all the latest pacts (with/without a tag) for all consumers for a provider from pact broker.
The pacts list is returned as an array where each element of an array is a hash with pact 'name' and 'href'  #key.
This makes it easier to obtain all the pacts for a provider dynamically and iterate through them in pact_helper.
An example of usage in pact_helper:
```pact_broker_client = PactBroker::Client::PactBrokerClient.new({base_url: PACT_BROKER})
pacts = pact_broker_client.pacticipants.versions.pacts.list_latest_for_provider provider: 'MyProvider', tag: 'prod'
pacts.each do |pact|
honours_pact_with pact[:name] do
pact_uri pact[:href]
end
end
```
> Add the option to retrieve all the latest (tagged) pacts for a provider

- spec/pacts/pact_broker_client-pact_broker.json
- spec/support/latest_pacts_for_provider.json
In order to fix the tests in pact-broker.
This will need to be merged to master for the pact-broker tests to pass again.
> Fix provider name in pact_broker_client-pact_broker.json

- README.md
@bethesque I keep getting confused with the two links haha. Um, I'm not sure if this is intentional or not, but I checked both repos and it looks like you're the active maintainer but the pact-foundation one is the more up-to-date one?
If I assumed incorrectly then feel free to close this :)
> Fix link to pact-broker

- README.md
I use a custom pact_dir in my consumer's Pact configuration. This custom setting conflicts with the task.pattern default, resulting in `PactBroker::Client::Error: No pact files found`.  I had to dig into https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/tasks/publication_task.rb to figure out task.pattern. Hopefully this small change to the README will help future users. 😃  Thank you for a wonderful tool! I love Pact!
> include task.pattern in README

- lib/pact_broker/client/can_i_deploy.rb
- spec/lib/pact_broker/client/can_i_deploy_spec.rb
Currently always 3 attempts are made, the value of the `retry-while-unknown` parameter is ignored.
```
time bin/pact-broker can-i-deploy --retry-while-unknown=10  -a 'foo' -e 'abcdefg1'
Computer says no ¯\_(ツ)_/¯ 
CONSUMER     | C.VERSION | PROVIDER             | P.VERSION                      | SUCCESS?
-------------|-----------|----------------------|--------------------------------|---------
foo | abcdefg1  |bar | ???                            | ???     
Missing one or more verification results
real	0m31.095s
user	0m0.447s
sys	0m0.122s
```
```
time bin/pact-broker can-i-deploy --retry-while-unknown=10 --retry-interval=60  -a 'foo' -e 'abcdefg1'
Computer says no ¯\_(ツ)_/¯ 
CONSUMER     | C.VERSION | PROVIDER             | P.VERSION                      | SUCCESS? …
```
> Fix retry-while-unknown logic

- README.md
This PR just puts the help output for `describe-version` into the readme.
I'd like to have longer documentation with examples, but I'm submitting this PR without examples because I'd like to link to this new section from the Pact Nirvana doc on pact.io (not yet published).
> docs: add help output for describe-version to the readme

- lib/pact_broker/client/cli/can_i_deploy_long_desc.txt
The variables names are incorrect and should not contain `BASE_URL_`.
> Fix invalid environment variable names in can-i-deploy docs

- pact-broker-client.gemspec
I think current thor dependancy is not suitable. Latest `pact_broker-client` needs ``~> 0.20.0` but Rails 6 need thor v1.0.1.
Bundler try to install suitable version with its dependancy; thus latest version is v1.13.0 in Rails app.
> Update thor dependancy

- README.md
Fixes #77 
This documents the common parameters for communicating with Pact Brokers:
* Optional environment variables to use instead of command line parameters
* Go into a little more detail on which authentication options you have and what's required
> Document broker communication parameters

- lib/pact_broker/client/matrix/abbreviate_version_number.rb
- spec/lib/pact_broker/client/matrix/abbreviate_version_number_spec.rb
We are using very long version numbers (to 2100 symbols) and lately, formatting has become really strange.
I don't know the idea behind the current code, so I don't know how to adapt it to a long version, so I just decided to trim it to 40 symbols.
> feat: trim long versions on can-i-deploy formatting

- README.md
- doc/pacts/markdown/Pact Broker Client - Pact Broker.md
- lib/pact_broker/client/cli/webhook_commands.rb
- lib/pact_broker/client/webhooks/create.rb
- spec/lib/pact_broker/client/cli/broker_run_webhook_commands_spec.rb
- spec/pacts/pact_broker_client-pact_broker.json
- spec/service_providers/webhooks_create_spec.rb
Add `--consumer-label` and `--provider-label` options to webhook create/update commands.
Related to https://github.com/pact-foundation/pact_broker/pull/501
> feat: Add participant label options to webhook create/update commands

- lib/pact_broker/client/cli/version_commands.rb
[v1.61.0](https://github.com/pact-foundation/pact_broker-client/releases/tag/v1.61.0) added code that uses ruby's safe navigation operator which was only available for ruby versions >= 2.3. Since this gem has ruby requirement of >= 2.0, this is creating issues for users using ruby < 2.3, such as users using the latest version (1.88.84) of [pact-foundation/pact-ruby-standalone](https://github.com/pact-foundation/pact-ruby-standalone) which ships with traveling ruby version of 2.2.
> fix: use ruby < 2.3 syntax.

- bin/pactflow
- doc/pacts/markdown/Pact Broker Client - Pactflow.md
- lib/pact_broker/client/hal_client_methods.rb
- lib/pactflow/client/cli/pactflow.rb
- lib/pactflow/client/cli/provider_contract_commands.rb
- lib/pactflow/client/provider_contracts/publish.rb
- script/oas.yml
- script/publish-provider-contract.sh
- script/verification-results.txt
- spec/pacts/pact_broker_client-pactflow.json
- spec/service_providers/pactflow_publish_provider_contract_spec.rb
example invocation:
```
pactflow publish-provider-contract  \
script/oas.yml \
--provider Foo \
--provider-app-version 1013b5650d61214e19f10558f97fb5a3bb082d44 \
--branch main \
--tag dev \
--specification oas \
--content-type application/yml \
--no-verification-success \
--verification-results script/verification-results.txt \
--verification-results-format text \
--verifier my-custom-tool \
--verifier-version "1.0"
```
> feat: add command to publish provider contracts

- .github/workflows/test.yml
- Dockerfile
* 2.6 is EOL and will no longer receive any updates, including security fixes. https://www.ruby-lang.org/en/downloads/branches/
* 2.2 has been EOL for more than four years now.
* 3.1 is now stable & current, not experimental.
This bumps the test matrix to purely the current versions of ruby, 2.7, 3.0 & 3.1
It also bumps the version of ruby in the Dockerfile to latest, but I don't think the Dockerfile is used to generate any distributed artifacts.
This goes along with the work to upgrade https://github.com/pact-foundation/pact-ruby-standalone from 2.2 to 2.4
> chore: bump ruby versions tested

- lib/pact_broker/client/base_command.rb
- lib/pact_broker/client/colorize_notices.rb
- lib/pactflow/client/provider_contracts/publish.rb
building on #118 it was identified that the colour contrast for the provider link was too dark and difficult to read on dark terminals.
Most times, your user may know what they need to do next, after interacting with the Pact Broker Client and a Pact Broker, however this is not always the case.
Authors should note that we use a mixture of text and colour, to convey
- actionable items
- informational items
- somethings gone awry items
We have tried to stick to these guidelines for user facing messages.
- `green` for success
- `white` for ancillary information
- `yellow` for next steps
- `red` for errors
- `magenta` for urls
So take for example publishing a pact.
- `green` successful publish
- `white` go and view your contract here
- `yellow` next steps
Utilises the `colorized_message` …
> feat: colour first url in magenta for ease of reading

- lib/pact_broker/client/cli/custom_thor.rb
Fixes the `pact-broker --help` command, so it doesn't attempt to source pact broker env vars`
prior behaviour
```console
bundle exec bin/pact-broker --help 
Could not find command "__broker_base_url".
```
```console
bundle exec bin/pact-broker help   
Commands:
pact-broker can-i-deploy -a, --pacticipant=PACTICIPANT -b, --broker-base-url=BROKER_BASE_URL                                                          # 
pact-broker create-environment --name=NAME -b, --broker-base-url=BROKER_BASE_URL                                                                      # Create an environment resource in the Pact Broker to represent a real world deployment or release environment.
pact-broker create-or-update-pacticipant --name=NAME -b, --broker-base-url=BROKER_BASE_URL …
```
> fix: pact-broker --help command now returns help commands

- README.md
- doc/pacts/markdown/Pact Broker Client - Pact Broker.md
- lib/pact_broker/client/branches/delete_branch.rb
- lib/pact_broker/client/cli/branch_commands.rb
- lib/pact_broker/client/cli/broker.rb
- script/update-cli-usage-in-readme.rb
- spec/lib/pact_broker/client/branches/delete_branch_spec.rb
- spec/pacts/pact_broker_client-pact_broker.json
- spec/service_providers/delete_branch_spec.rb
- spec/service_providers/pact_helper.rb
> feat: add support for delete-branch command

- lib/pact_broker/client/cli/matrix_commands.rb
Trying out this command returned the following error
`PACT_BROKER_FEATURES=verification_required pact-broker verification-required --pacticipant=FrontEndService --version foo`
Error:-
```
/opt/homebrew/Cellar/pact-ruby-standalone/2.0.9/lib/vendor/ruby/3.2.0/gems/pact_broker-client-1.74.0/lib/pact_broker/client/can_i_deploy.rb:22:in `call': wrong number of arguments (given 5, expected 3..4) (ArgumentError)
from /opt/homebrew/Cellar/pact-ruby-standalone/2.0.9/lib/vendor/ruby/3.2.0/gems/pact_broker-client-1.74.0/lib/pact_broker/client/cli/matrix_commands.rb:91:in `verification_required'
from /opt/homebrew/Cellar/pact-ruby-standalone/2.0.9/lib/vendor/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
from /opt/homebrew/Cellar/pact-ruby-standalone/2.0.9/lib/vendor/ruby/3.2.0/gems/thor-1 …
```
> fix: verification-required command invalid arg number

- .github/workflows/test.yml
- lib/pact_broker/client/pacts/list_latest_versions.rb
- lib/pact_broker/client/publish_pacts.rb
- lib/pact_broker/client/webhooks/create.rb
- lib/pactflow/client/provider_contracts/publish.rb
- lib/pactflow/client/provider_contracts/publish_the_old_way.rb
- spec/integration/can_i_merge_spec.rb
- spec/lib/pact_broker/client/cli/broker_can_i_deploy_spec.rb
- spec/lib/pact_broker/client/cli/broker_publish_spec.rb
- spec/lib/pact_broker/client/cli/broker_run_webhook_commands_spec.rb
- spec/lib/pactflow/client/provider_contracts/publish_spec.rb
So as of the latest release of pact-ruby-cli, we had some errors reported
`NameError - uninitialized constant Pactflow::Client::ProviderContracts::Publish::OpenStruct`
https://github.com/pact-foundation/pact-ruby-cli/issues/131
passing the following env var
`-e RUBYOPT="-rostruct"`
fixes it, temporarily for end users.
```sh
docker run -v $PWD:/home --rm -it -e PACT_BROKER_TOKEN -e PACT_BROKER_BASE_URL -e RUBYOPT="-rostruct" pactfoundation/pact-cli:latest pactflow publish-provider-contract /home/example/provider-contracts/oas.yml --provider foo --provider-app-version foo1 --content-type application/yaml 
```
Interesting, re-running our CI today, with no code changes other than adding in ruby 3.3 to the matrix, resulted in the same test failures. …
> fix: openstruct broken unless explicit require of ostruct

- pact-broker-client.gemspec
fixes #139
Also relates to https://github.com/pact-foundation/pact-ruby-cli/issues/123
> fix: remove test files from built gem

- lib/pact_broker/client/can_i_deploy.rb
- spec/lib/pact_broker/client/can_i_deploy_spec.rb
fixes #149
When --dry-run is enabled, --retry-while-unknown will no longer take effect.
> feat(can-i-deploy): skip --retry-while-unknown if --dry-run true

- pact-broker-client.gemspec
Fixes issue #173
This PR addresses the warning related to the `ostruct` library being removed from the standard library in Ruby 3.5.0 by adding it as an explicit dependency in the gemspec file.
> fix: ostruct was loaded from the standard library
